{% set name = "opencadd" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/volkamerlab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: bd512c485f41496cd1f73f5fa2a98ce90cde525a080c1df25bdf63a2e073ae11

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - matplotlib-base
    - mdanalysis
    - nglview
    - bravado
    - biopandas
    - rdkit
    - tqdm
    - biotite
    - biopython <=1.77
    # Not available under Windows yet
    #- mmligner
    #- theseus

test:
  imports:
    - opencadd

about:
  home: https://github.com/volkamerlab/opencadd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for structural cheminformatics
  description: |
    A Python library for structural cheminformatics
  doc_url: https://opencadd.readthedocs.io/en/latest
  dev_url: https://github.com/volkamerlab/opencadd

extra:
  recipe-maintainers:
    - dominiquesydow
    - jaimergp
